### ISSUE TITLE
mumble-registration.yaml location should not be hardcoded

### ISSUE THREAD

**Issue by bertiebaggio** [bertiebaggio/matrix-appservice-mumble-docker#2]
https://github.com/bertiebaggio/matrix-appservice-mumble-docker/blob/504ce43760166bce00d122943533161546027805/src/main.ts#L15

Location of mumble-registration.yaml seems to be hardcoded to app working dir, at least AFAICT from above.

This is an inconvenience / untidiness from a volumes point of view for integration with MDAD, since it needs to be specifically mapped to MAM work dir.

**Comment by bertiebaggio** [comment]
Further, if the registration file location is specified as being elsewhere with `-f`, the app give an ` ENOENT` error:
```
matrix-appservice-mumble | (node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'mumble-registration.yaml'
matrix-appservice-mumble |     at Object.openSync (fs.js:476:3)
matrix-appservice-mumble |     at Object.readFileSync (fs.js:377:35)
matrix-appservice-mumble |     at Bridge.run (/mam/node_modules/matrix-appservice-bridge/lib/bridge.js:278:39)
matrix-appservice-mumble |     at Object.<anonymous> (/mam/build/main.js:252:44)
matrix-appservice-mumble |     at step (/mam/build/main.js:44:23)
matrix-appservice-mumble |     at Object.next (/mam/build/main.js:25:53)
matrix-appservice-mumble |     at fulfilled (/mam/build/main.js:16:58)
matrix-appservice-mumble |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
matrix-appservice-mumble | (Use `node --trace-warnings ...` to show where the warning was created)
matrix-appservice-mumble | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
matrix-appservice-mumble | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So the app requires both the file to be present at the location specified by `-f` and in the working directory.
